version: "3"
services:
  kaggle-training:
    container_name: 'kaggle-training'
    command: bash -c "jupyter lab --notebook-dir=/home/kaggle-training --ip='0.0.0.0' --port=8888 --no-browser --allow-root"
    build: .
    ports:
      - '8888:8888'
    volumes:
      - ./:/home/kaggle-training
